resource.AddFile( "models/nova/airboat_seat.mdl" )

resource.AddFile( "models/military2/air/air_130_l.mdl" )
resource.AddFile( "models/harrier.mdl" )

resource.AddFile( "models/military2/bomb/bomb_gbu10.mdl" )
resource.AddFile( "models/military2/bomb/bomb_jdam.mdl" )

resource.AddFile( "models/military2/missile/missile_s300.mdl" )
resource.AddFile( "models/military2/missile/missile_sm2.mdl" )

--Gibs
resource.AddFile( "models/military2/air/gibs/backleftwing.mdl" )
resource.AddFile( "models/military2/air/gibs/backrightwing.mdl" )
resource.AddFile( "models/military2/air/gibs/cockpit.mdl" )
resource.AddFile( "models/military2/air/gibs/frontwheel.mdl" )
resource.AddFile( "models/military2/air/gibs/leftwheel.mdl" )
resource.AddFile( "models/military2/air/gibs/leftwing.mdl" )
resource.AddFile( "models/military2/air/gibs/middle.mdl" )
resource.AddFile( "models/military2/air/gibs/rightwheel.mdl" )
resource.AddFile( "models/military2/air/gibs/rightwing.mdl" )



//Sound
resource.AddFile( "sound/killstreak_rewards/ac-130_25mm_fire.wav" )
resource.AddFile( "sound/killstreak_rewards/ac-130_40mm_fire.wav" )
resource.AddFile( "sound/killstreak_rewards/ac-130_105mm_fire.wav" )
resource.AddFile( "sound/killstreak_rewards/ac-130_acquired1.wav" )
resource.AddFile( "sound/killstreak_rewards/ac-130_acquired2.wav" )
resource.AddFile( "sound/killstreak_rewards/ac-130_acquired3.wav" )
resource.AddFile( "sound/killstreak_rewards/ac-130_acquired4.wav" )
resource.AddFile( "sound/killstreak_rewards/ac-130_acquired5.wav" )
resource.AddFile( "sound/killstreak_rewards/ac-130_deploy.wav" )

resource.AddFile( "sound/killstreak_rewards/harrier_acquired1.wav" )
resource.AddFile( "sound/killstreak_rewards/harrier_acquired2.wav" )
resource.AddFile( "sound/killstreak_rewards/harrier_acquired3.wav" )
resource.AddFile( "sound/killstreak_rewards/harrier_acquired4.wav" )
resource.AddFile( "sound/killstreak_rewards/harrier_acquired5.wav" )
resource.AddFile( "sound/killstreak_rewards/harrier_hover.wav" )
resource.AddFile( "sound/killstreak_rewards/harrier_laptop.wav" )
resource.AddFile( "sound/killstreak_rewards/harrier_shoot.wav" )

resource.AddFile( "sound/killstreak_rewards/predator_missile_acquired1.wav" )
resource.AddFile( "sound/killstreak_rewards/predator_missile_acquired2.wav" )
resource.AddFile( "sound/killstreak_rewards/predator_missile_acquired3.wav" )
resource.AddFile( "sound/killstreak_rewards/predator_missile_acquired4.wav" )
resource.AddFile( "sound/killstreak_rewards/predator_missile_acquired5.wav" )
resource.AddFile( "sound/killstreak_rewards/predator_missile_boost.wav" )
resource.AddFile( "sound/killstreak_rewards/predator_missile_deploy.wav" )
resource.AddFile( "sound/killstreak_rewards/predator_missile_explosion.wav" )
resource.AddFile( "sound/killstreak_rewards/predator_missile_inbound.wav" )
resource.AddFile( "sound/killstreak_rewards/predator_missile_thruster.wav" )

resource.AddFile( "sound/killstreak_rewards/uav_deploy.wav" )
resource.AddFile( "sound/killstreak_rewards/uav_acquired1.wav" )
resource.AddFile( "sound/killstreak_rewards/uav_acquired2.wav" )
resource.AddFile( "sound/killstreak_rewards/uav_acquired3.wav" )
resource.AddFile( "sound/killstreak_rewards/uav_acquired4.wav" )
resource.AddFile( "sound/killstreak_rewards/uav_acquired5.wav" )

//Materials
resource.AddFile( "materials/models/military2/air/air_f35_pitpanel.vtf" )
resource.AddFile( "materials/models/military2/air/air_f35_side.vtf" )
resource.AddFile( "materials/models/military2/air/air_f35_tail.vtf" )
resource.AddFile( "materials/models/military2/air/air_f35_tail_nomal.vtf" )
resource.AddFile( "materials/models/military2/air/air_f35_top.vtf" )
resource.AddFile( "materials/models/military2/air/air_f35_top_nomal.vtf" )
resource.AddFile( "materials/models/military2/air/air_f35_wing1.vtf" )
resource.AddFile( "materials/models/military2/air/air_f35_wing1_nomal.vtf" )
resource.AddFile( "materials/models/military2/air/air_f35_wing2.vtf" )
resource.AddFile( "materials/models/military2/air/air_f35_wing2_nomal.vtf" )
resource.AddFile( "materials/models/military2/air/air_f35_bot.vtf" )
resource.AddFile( "materials/models/military2/air/air_f35_bot_nomal.vtf" )
resource.AddFile( "materials/models/military2/air/air_f35_hood.vtf" )
resource.AddFile( "materials/models/military2/air/air_f35_int_int.vtf" )
resource.AddFile( "materials/models/military2/air/air_f35_nose.vtf" )
resource.AddFile( "materials/models/military2/air/air_f35_nose_nomal.vtf" )
resource.AddFile( "materials/models/military2/air/air_f35_noz_3.vtf" )
resource.AddFile( "materials/models/military2/air/air_f35_noz_3_nomal.vtf" )
resource.AddFile( "materials/models/military2/air/air_f35_pitbars.vtf" )
resource.AddFile( "materials/models/military2/air/air_seat_frnt.vtf" )
resource.AddFile( "materials/models/military2/air/air_frontglass.vtf" )
resource.AddFile( "materials/models/military2/air/air_gear_r1.vtf" )
resource.AddFile( "materials/models/military2/air/air_gear_r2.vtf" )
resource.AddFile( "materials/models/military2/air/air_glass.vtf" )
resource.AddFile( "materials/models/military2/air/air_seat_head1.vtf" )
resource.AddFile( "materials/models/military2/air/air_pylon2.vtf" )
resource.AddFile( "materials/models/military2/air/air_int2.vtf" )
resource.AddFile( "materials/models/military2/air/air_f15e_wheel.vtf" )
resource.AddFile( "materials/models/military2/air/air_f15e_engine.vtf" )
resource.AddFile( "materials/models/military2/air/air_f15e_engine_nomal.vtf" )

resource.AddFile( "materials/models/military2/bomb/bomb_cbutex.vtf" )
resource.AddFile( "materials/models/military2/bomb/bomb_cbutex_nomal.vtf" )

resource.AddFile( "materials/models/military2/missile/missile_AGM88E.vtf" )
resource.AddFile( "materials/models/military2/missile/missile_AGM88E_nomal.vtf" )

resource.AddFile( "materials/VGUI/entities/sent_SakariasJet.vtf" )
